services:
  view:
    build:
      context: ./view
    volumes:
      - ./view:/app
      - ./view/.pnpm-store:/app/.pnpm-store
    ports:
      - "3000:3000"
    command: ["sh", "-c", "pnpm install && pnpm dev"]

  api:
    build:
      context: ./api
      dockerfile: api.Dockerfile
    container_name: api
    ports:
      - "8000:8000"
    env_file:
      - api.env  # 環境変数を api.env から読み込む
    environment:
      RAILS_ENV: production
      BUNDLE_DEPLOYMENT: "1"
      BUNDLE_PATH: "/usr/local/bundle"
      BUNDLE_WITHOUT: "development"
      PORT: "8000"
    volumes:
      - ./api:/rails  # ローカルの api ディレクトリをコンテナの /rails にマウント
    restart: always
