services:
  view:
    build:
      context: ./view
    volumes:
      - ./view:/app
      - ./view/.pnpm-store:/app/.pnpm-store
    ports:
      - "3000:3000"
    env_file:
      - view.env
    command: ["sh", "-c", "pnpm install && pnpm dev"]

  cloudflare:
    image: "cloudflare/cloudflared:2025.2.1"
    container_name: "cloudflare"
    volumes: [ './cloudflare:/home/nonroot/.cloudflared' ]
    command: tunnel run
    restart: unless-stopped
