services:
  cloudflare:
    image: "cloudflare/cloudflared:2025.2.1"
    container_name: "cloudflare"
    volumes: [ './cloudflare:/home/nonroot/.cloudflared' ]
    command: tunnel run
    restart: unless-stopped
  view:
    build:
      context: ./view
      dockerfile: prod.Dockerfile
      args:
        - NEXT_PUBLIC_APP_ENV=${NEXT_PUBLIC_APP_ENV}
        - NEXT_PUBLIC_APIKEY=${NEXT_PUBLIC_APIKEY}
        - NEXT_PUBLIC_AUTHDOMAIN=${NEXT_PUBLIC_AUTHDOMAIN}
        - NEXT_PUBLIC_PROJECTID=${NEXT_PUBLIC_PROJECTID}
        - NEXT_PUBLIC_STORAGEBUCKET=${NEXT_PUBLIC_STORAGEBUCKET}
        - NEXT_PUBLIC_MESSAGINGSENDERID=${NEXT_PUBLIC_MESSAGINGSENDERID}
        - NEXT_PUBLIC_APPID=${NEXT_PUBLIC_APPID}
        - NEXT_PUBLIC_MEASUREMENTID=${NEXT_PUBLIC_MEASUREMENTID}
        - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
        - NEXT_PUBLIC_MAGAZINE_URL=${NEXT_PUBLIC_MAGAZINE_URL}
    container_name: prod-view
    ports:
      - "3000:3000"

  api:
    build:
      context: ./api
      dockerfile: prod.Dockerfile
    container_name: prod-api
    ports:
      - "8000:8000"
    env_file:
      - .env  # 環境変数を api.env から読み込む
    environment:
      RAILS_ENV: production
      BUNDLE_DEPLOYMENT: "1"
      BUNDLE_PATH: "/usr/local/bundle"
      PORT: "8000"
    volumes:
      - ./api:/api  # ローカルの api ディレクトリをコンテナの /api にマウント
    restart: always

  magazine:
    build:
      context: ./magazine
      dockerfile: prod.Dockerfile
    volumes:
      - ./magazine:/magazine
    container_name: prod-magazine
    ports:
      - "9004:9004"
    env_file:
      - .env

  db:
    image: postgres:15
    container_name: prod_postgres_db
    restart: always
    env_file:
      - .env
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
