services:
  view:
    build:
      context: ./view
    volumes:
      - ./view:/app
      - ./view/.pnpm-store:/app/.pnpm-store
    ports:
      - "3000:3000"
    env_file:
      - view.env
    command: ["sh", "-c", "pnpm install && pnpm dev"]

  api:
    build:
      context: ./api
    container_name: api
    ports:
      - "8000:8000"
    env_file:
      - api.env  # 環境変数を api.env から読み込む
    environment:
      RAILS_ENV: development
      BUNDLE_DEPLOYMENT: "1"
      BUNDLE_PATH: "/usr/local/bundle"
      PORT: "8000"
    volumes:
      - ./api:/api  # ローカルの api ディレクトリをコンテナの /api にマウント
      - bundle-data:/usr/local/bundle
    restart: always
  #フロントとバックの通信(FastAPI)の環境

  magazine:
    build:
      context: ./magazine
    volumes:
      - ./magazine:/magazine
    ports:
      - "9004:9004"
    command: uvicorn main:app --reload --host 0.0.0.0 --port 9004
    env_file:
      - magazine.env

  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: myapp_development
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  bundle-data:

