name: Cross repo
on: push

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Create github app token
        id: create
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_KEY }}
          repositories: ${{ secrets.TARGET_REPO }}

      - name: Checkout target repo
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository_owner }}/${{ secrets.TARGET_REPO }}
          path: ${{ github.event.repository.name }}
          token: ${{ steps.create.outputs.token }}
