name: Release Docker Build and Push

on:
  workflow_run:
    workflows: ["Release action"] # 完了を待つワークフロー名
    types:
      - completed

jobs:
  build-and-push:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - context: api
            dockerfile: prod.Dockerfile
            image_name: sharehause/oshi-ramen-api
          - context: view
            dockerfile: prod.Dockerfile
            image_name: sharehause/oshi-ramen-view
          - context: magazine
            dockerfile: prod.Dockerfile
            image_name: sharehause/oshi-ramen-magazine

    steps:
      # 1. リポジトリのチェックアウト
      - name: Checkout Repository
        uses: actions/checkout@v4

      # 2. Secretsから.envファイルを作成
      - name: Create .env file from Secrets
        run: echo "${{ secrets.PROD_ENV }}" > .env

      # 3. .envファイルの内容をbuild-argsとして利用できるように整形
      - name: Generate build args from .env
        id: build_args
        run: |
          echo "args<<EOF" >> $GITHUB_OUTPUT
          cat .env >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      # 4. 最新のタグを取得するシェルスクリプトを実行
      - name: Get latest tag
        id: get_tag
        run: |
          # タグ情報を最新にするためにfetchする
          git fetch --tags
          latest_tag=$(git tag --sort=-v:refname | head -n 1)
          echo "Latest tag: $latest_tag"
          echo "latest_tag=$latest_tag" >> $GITHUB_OUTPUT

      # 5. Docker Buildxのセットアップ
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # 6. Docker Hubへログイン
      - name: Docker Login
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.HARBOR_REG }}
          username: ${{ secrets.HARBOR_USERNAME }}
          password: ${{ secrets.HARBOR_PASS }}

      # 7. Dockerイメージのビルドとpush（最新タグを利用）
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./${{ matrix.context }}
          file: ${{ matrix.dockerfile }}
          push: true
          tags: |
            ${{ matrix.image_name }}:${{ steps.get_tag.outputs.latest_tag }}
            ${{ matrix.image_name }}:latest
          build-args: ${{ steps.build_args.outputs.args }}
